#include <stdio.h>
int main() {

    printf("GOOD MORNING TO EVERYONE\n");
    printf("Today i want to intoduce my self\n");
    printf("==============================================ABOUT MEEE=================================================\n");
    printf("this is G.vijaya akshaya\n");
    printf("\n");
    printf("from 1st year of artificial inteligence and data science\n");
    printf("studying in SSECT\n");
    printf("near sankari\n");
        printf("\n");
        printf("MY PRESENT DETAILS\n");
        printf("GOAL: is data analyst\t");
        printf("currently i am in my second semister\t");
    printf("In there i atterned so many training programs like\n");
    printf("communication training program\t");
    printf("c programming\t");
    printf("inspire program\t");
printf("\n");
    printf(" ...........................................ABOUT MY EDUCATION...............................................\n");
    printf("\n");
    printf("i am completing my 10th in mks english medium high school \t");
    printf("with the grade 9.2\t");
    printf("after i am completed my 11th and 12th in Sri chaithanya institutions\t");
    printf("with the grade 9.4\t");
    printf("now i am studying b.tech first year\t");
    printf("in first grade i got 8.17 CGPA\t");
    printf("\n");
    printf("-------------------------------------------About FAMILY---------------------------------------------------------\n");
    printf("\n");
    printf(" first of all i introduced my family\t");
    printf(" it  is a nuclear family\t");
    printf(" In my family there are four numbers are there\t");
    printf("I love my parents very much\t");
    printf("They are also love us like that way only\t");
    printf("My father name is:Ravikumar\t");
    printf("he is a prist\t");
    printf("In my  village only\t");
    printf("My mother name is: naga jyothi \t");
    printf("she is a house wife:\n");
    printf("i have one sister\t");
    printf("her name is amulya\t");
    printf("she is completed 12th\t");
    printf("she was intersted in engineering\n");
    printf("I love my parents very much\t");
    printf("They are also love us like that way i like them\n");
    printf("\n");
    printf("************************************************MY PERSONAL DETAILS******************************************************\n");
    printf("\n");
    printf("..........MY FAV .........\n");
    printf("COLOUR:it is black\n");
    printf("FAV BOOK:the art of being alone\n");
    printf("PLACE:it is kedharnath\n");
    printf(" GOD:krishna\n");
    printf("HERO:prabhas\n");
    printf("HEROINE:Anupama parameswaran\n");
    printf("FOOD:pani puri\n");
    printf("FRY:potato\n");
    printf("FAV THINGS TO DO IN LEASURE TIME:playing games,eating,reading books & iritating some one\n");
    printf("MOVIE:sitharam\n");
    printf("SONG:mallikagandha\n");
    printf(" FRIEND:tikki\n");
    printf("SNACK:bajji");
    printf("FRUIT:MANGOOO\n");
    printf("FAV SEASON:rainy\n");
    printf("CHILDHOOD GOAL:teacher");
    printf("IN FREE TIME:scroling reels\n");
    printf("USING MOBILE:every time");
    printf("FAV SPORt:kabaddi\n");
    printf("HOBBY:sleeping\n");
    printf("FAV LETTER:|'p'|\n");
    printf("FAV SPot:sitting alone\n");
    printf("BIRD :peacock\n");
    printf("FAV ACTIVITY:sighting for bujjiman \n");
    printf("planting is my nature to do in home\n");
    printf("\n");
printf("                                         ABOUT MY TRAINING PROGRAMS                                                    \n");
printf("\n");
printf("IM MY COMMENICATION TRAINING\n");
printf("in Stsrting i am fear to talking with others\v");
printf("because of fear of judgements\v");
printf("my frnds were talking in english well\v");
printf("then i realise i also want to talk\v");
printf("i also partisipate in some activities like that\v");
printf("then i try to active in all\v");
printf("when i try to participate am afride to talk in front of people\v");
printf("because of lack of confidence\v");
printf("in that time two of my frnds are motivate me a lot and they give more confidence\v");
printf("also they push me to do that activities like that\v");
printf("noe also am fear and when i try to talk in stage \v");
printf("i forgot everything\v");
printf("SECOND THE TECHNICAL\v");
printf("before that i dont know how to write a code any thing\v");
printf("after 6 days of training i learn some thing about coding\v");
printf("then i didnot touch it after 45days\v");
printf("the clg management they conducted the c programming training\v");
printf("its take the three months to learn obly the basics\v");
printf("After that the traning was stopped\v");
printf("then i will did't stopped any thing i learn the basics and other thing\v");
printf("in that only i am doing consistancyly and make a goal and choosen my domain\v");
printf("after the inspire program was happend it gives my confidence \v");
printf("these programs helps me a lot to get confidence and improve my communication a little better\v");



    
    return 0;
}